// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLsMNhO60qsWS0_W-ssEiQM2wlGhyDPPw',
    appId: '1:511070374189:web:12041f1bce8a492a55aba4',
    messagingSenderId: '511070374189',
    projectId: 'lumiere-aba7f',
    authDomain: 'lumiere-aba7f.firebaseapp.com',
    storageBucket: 'lumiere-aba7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pjUajGXIoTSl9CVKct6ZloYOvIIUtwE',
    appId: '1:511070374189:android:7f1946e57df9f08755aba4',
    messagingSenderId: '511070374189',
    projectId: 'lumiere-aba7f',
    storageBucket: 'lumiere-aba7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTYMdjsjPwAR65wUk6mKyRW1BJ4BSulU',
    appId: '1:511070374189:ios:f59cd4d6f17454d955aba4',
    messagingSenderId: '511070374189',
    projectId: 'lumiere-aba7f',
    storageBucket: 'lumiere-aba7f.firebasestorage.app',
    iosBundleId: 'com.example.lumiere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtTYMdjsjPwAR65wUk6mKyRW1BJ4BSulU',
    appId: '1:511070374189:ios:f59cd4d6f17454d955aba4',
    messagingSenderId: '511070374189',
    projectId: 'lumiere-aba7f',
    storageBucket: 'lumiere-aba7f.firebasestorage.app',
    iosBundleId: 'com.example.lumiere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLsMNhO60qsWS0_W-ssEiQM2wlGhyDPPw',
    appId: '1:511070374189:web:426c4aea57d01e1955aba4',
    messagingSenderId: '511070374189',
    projectId: 'lumiere-aba7f',
    authDomain: 'lumiere-aba7f.firebaseapp.com',
    storageBucket: 'lumiere-aba7f.firebasestorage.app',
  );
}
